name: Deploy to Nekoweb

on:
    push:
        branches:
            - lyra

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Upload site to Nekoweb
              env:
                  NEKOWEB_API_KEY: ${{ secrets.NEKOWEB_API_KEY }}
              run: |
                  set -e

                  for file in $(find . -type f \
                    ! -path "./.git/*" \
                    ! -path "./.github/*"); do

                    relpath="${file#./}"
                    echo "Uploading $relpath"

                    curl --request POST \
                      -url https://nekoweb.org/api/files/upload \
                      -header "Authorization: $NEKOWEB_API_KEY" \
                      -form pathname=/test \
                      --form files=@"$file"
                  done
