name: Deploy to Nekoweb

on:
    push:
        branches:
            - lyra

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Upload site to Nekoweb
              env:
                  NEKOWEB_API_KEY: ${{ secrets.NEKOWEB_API_KEY }}
              run: |
                  set -e

                  find . -type f \
                      ! -path "./.git/*" \
                      ! -path "./.github/*" \
                      ! -name "*.zip" | while read file; do

                      relpath="${file#./}"
                      dirpath="$(dirname "$relpath")"
                      
                      if [ "$dirpath" = "." ]; then
                        uploadpath="/meowbyte.nekoweb.org"
                      else
                        uploadpath="/meowbyte.nekoweb.org/$dirpath"
                      fi

                      echo "Uploading $relpath to $uploadpath"

                      curl --request POST \
                      --url https://nekoweb.org/api/files/upload \
                      --header "Authorization: $NEKOWEB_API_KEY" \
                      --form pathname=$uploadpath \
                      --form files=@"$file"
                  done
